/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 58
#define LARGE_STATE_COUNT 11
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 1
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_shebang = 1,
  aux_sym_word_token1 = 2,
  anon_sym_DASH = 3,
  aux_sym_word_token2 = 4,
  anon_sym_SQUOTE = 5,
  anon_sym_BSLASH = 6,
  anon_sym_LBRACK = 7,
  anon_sym_RBRACK = 8,
  anon_sym_LPAREN = 9,
  aux_sym_comment_token1 = 10,
  anon_sym_RPAREN = 11,
  anon_sym_DQUOTE = 12,
  anon_sym_n = 13,
  anon_sym_e = 14,
  anon_sym_r = 15,
  anon_sym_t = 16,
  aux_sym_string_token1 = 17,
  sym_raw_string_content = 18,
  anon_sym_BQUOTE = 19,
  sym_number = 20,
  sym_program = 21,
  sym__expr = 22,
  sym_word = 23,
  sym_symbol = 24,
  sym_unquote = 25,
  sym_block = 26,
  sym_comment = 27,
  sym_string_escape = 28,
  sym_string = 29,
  sym_raw_string = 30,
  aux_sym_program_repeat1 = 31,
  aux_sym_comment_repeat1 = 32,
  aux_sym_string_repeat1 = 33,
  alias_sym_sentence = 34,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_shebang] = "shebang",
  [aux_sym_word_token1] = "word_token1",
  [anon_sym_DASH] = "-",
  [aux_sym_word_token2] = "word_token2",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_n] = "n",
  [anon_sym_e] = "e",
  [anon_sym_r] = "r",
  [anon_sym_t] = "t",
  [aux_sym_string_token1] = "string_token1",
  [sym_raw_string_content] = "raw_string_content",
  [anon_sym_BQUOTE] = "`",
  [sym_number] = "number",
  [sym_program] = "program",
  [sym__expr] = "_expr",
  [sym_word] = "word",
  [sym_symbol] = "symbol",
  [sym_unquote] = "unquote",
  [sym_block] = "block",
  [sym_comment] = "comment",
  [sym_string_escape] = "string_escape",
  [sym_string] = "string",
  [sym_raw_string] = "raw_string",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_comment_repeat1] = "comment_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [alias_sym_sentence] = "sentence",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_shebang] = sym_shebang,
  [aux_sym_word_token1] = aux_sym_word_token1,
  [anon_sym_DASH] = anon_sym_DASH,
  [aux_sym_word_token2] = aux_sym_word_token2,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_n] = anon_sym_n,
  [anon_sym_e] = anon_sym_e,
  [anon_sym_r] = anon_sym_r,
  [anon_sym_t] = anon_sym_t,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_raw_string_content] = sym_raw_string_content,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [sym_number] = sym_number,
  [sym_program] = sym_program,
  [sym__expr] = sym__expr,
  [sym_word] = sym_word,
  [sym_symbol] = sym_symbol,
  [sym_unquote] = sym_unquote,
  [sym_block] = sym_block,
  [sym_comment] = sym_comment,
  [sym_string_escape] = sym_string_escape,
  [sym_string] = sym_string,
  [sym_raw_string] = sym_raw_string,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [alias_sym_sentence] = alias_sym_sentence,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_shebang] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_word_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_word_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_n] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_r] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_t] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_raw_string_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_unquote] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_string_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_sentence] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_content = 1,
  field_string_content = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
  [field_string_content] = "string_content",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [3] = {.index = 0, .length = 1},
  [4] = {.index = 1, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_content, 1},
  [1] =
    {field_string_content, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_sentence,
  },
  [2] = {
    [1] = alias_sym_sentence,
  },
  [3] = {
    [1] = alias_sym_sentence,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym_program_repeat1, 2,
    aux_sym_program_repeat1,
    alias_sym_sentence,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 6,
  [8] = 8,
  [9] = 4,
  [10] = 5,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 11,
  [20] = 12,
  [21] = 21,
  [22] = 18,
  [23] = 13,
  [24] = 14,
  [25] = 15,
  [26] = 16,
  [27] = 17,
  [28] = 28,
  [29] = 21,
  [30] = 28,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 32,
  [35] = 35,
  [36] = 35,
  [37] = 37,
  [38] = 38,
  [39] = 37,
  [40] = 38,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 43,
  [45] = 45,
  [46] = 46,
  [47] = 46,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 50,
  [54] = 54,
  [55] = 54,
  [56] = 49,
  [57] = 51,
};

static const TSCharacterRange aux_sym_word_token2_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'#', '&'}, {'*', '/'}, {':', ':'}, {'<', 'Z'}, {'^', '_'},
  {'a', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      ADVANCE_MAP(
        '"', 28,
        '#', 1,
        '\'', 19,
        '(', 23,
        ')', 27,
        '-', 16,
        '0', 38,
        '[', 21,
        '\\', 20,
        ']', 22,
        '`', 37,
        'e', 30,
        'n', 29,
        'r', 31,
        't', 32,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(28);
      if (lookahead == '(') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(23);
      if (lookahead == ')') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 4:
      if (lookahead == '(') ADVANCE(23);
      if (lookahead == '-') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (lookahead != 0 &&
          lookahead != '"' &&
          (lookahead < '\'' || ')' < lookahead) &&
          (lookahead < '0' || '9' < lookahead) &&
          lookahead != ';' &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '`') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(42);
      END_STATE();
    case 9:
      if (eof) ADVANCE(11);
      ADVANCE_MAP(
        '"', 28,
        '#', 14,
        '\'', 19,
        '(', 23,
        '-', 16,
        '0', 38,
        '[', 21,
        '\\', 20,
        '`', 37,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(39);
      if (lookahead != 0 &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != ';' &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(15);
      END_STATE();
    case 10:
      if (eof) ADVANCE(11);
      ADVANCE_MAP(
        '"', 28,
        '\'', 19,
        '(', 23,
        '-', 16,
        '0', 38,
        '[', 21,
        '\\', 20,
        ']', 22,
        '`', 37,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(39);
      if (lookahead != 0 &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != ';') ADVANCE(15);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_shebang);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          ('\'' <= lookahead && lookahead <= ')') ||
          lookahead == ';' ||
          ('[' <= lookahead && lookahead <= ']') ||
          lookahead == '`') ADVANCE(13);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_shebang);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (lookahead == '!') ADVANCE(12);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          (lookahead < ' ' || '"' < lookahead) &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != ';' &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '`') ADVANCE(15);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if ((!eof && set_contains(aux_sym_word_token2_character_set_1, 9, lookahead)) ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '0') ADVANCE(38);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(39);
      if ((!eof && set_contains(aux_sym_word_token2_character_set_1, 9, lookahead))) ADVANCE(18);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DASH);
      if ((!eof && set_contains(aux_sym_word_token2_character_set_1, 9, lookahead))) ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_word_token2);
      if ((!eof && set_contains(aux_sym_word_token2_character_set_1, 9, lookahead)) ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(36);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(25);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_n);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_e);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_r);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_t);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '(') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(33);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_raw_string_content);
      if (lookahead == '(') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_raw_string_content);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(6);
      if (lookahead == 'o') ADVANCE(7);
      if (lookahead == 'x') ADVANCE(8);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(6);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(42);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 9},
  [2] = {.lex_state = 10},
  [3] = {.lex_state = 10},
  [4] = {.lex_state = 10},
  [5] = {.lex_state = 10},
  [6] = {.lex_state = 10},
  [7] = {.lex_state = 10},
  [8] = {.lex_state = 10},
  [9] = {.lex_state = 10},
  [10] = {.lex_state = 10},
  [11] = {.lex_state = 10},
  [12] = {.lex_state = 10},
  [13] = {.lex_state = 10},
  [14] = {.lex_state = 10},
  [15] = {.lex_state = 10},
  [16] = {.lex_state = 10},
  [17] = {.lex_state = 10},
  [18] = {.lex_state = 10},
  [19] = {.lex_state = 10},
  [20] = {.lex_state = 10},
  [21] = {.lex_state = 10},
  [22] = {.lex_state = 10},
  [23] = {.lex_state = 10},
  [24] = {.lex_state = 10},
  [25] = {.lex_state = 10},
  [26] = {.lex_state = 10},
  [27] = {.lex_state = 10},
  [28] = {.lex_state = 10},
  [29] = {.lex_state = 10},
  [30] = {.lex_state = 10},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 4},
  [39] = {.lex_state = 4},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 35},
  [55] = {.lex_state = 35},
  [56] = {(TSStateId)(-1),},
  [57] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_shebang] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [aux_sym_word_token2] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(3),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_n] = ACTIONS(1),
    [anon_sym_e] = ACTIONS(1),
    [anon_sym_r] = ACTIONS(1),
    [anon_sym_t] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_program] = STATE(52),
    [sym__expr] = STATE(18),
    [sym_word] = STATE(29),
    [sym_symbol] = STATE(29),
    [sym_unquote] = STATE(29),
    [sym_block] = STATE(29),
    [sym_comment] = STATE(1),
    [sym_string] = STATE(29),
    [sym_raw_string] = STATE(29),
    [aux_sym_program_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_shebang] = ACTIONS(7),
    [aux_sym_word_token1] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(9),
    [aux_sym_word_token2] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_BSLASH] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(19),
    [anon_sym_BQUOTE] = ACTIONS(21),
    [sym_number] = ACTIONS(23),
  },
  [STATE(2)] = {
    [sym__expr] = STATE(18),
    [sym_word] = STATE(29),
    [sym_symbol] = STATE(29),
    [sym_unquote] = STATE(29),
    [sym_block] = STATE(29),
    [sym_comment] = STATE(2),
    [sym_string] = STATE(29),
    [sym_raw_string] = STATE(29),
    [aux_sym_program_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(25),
    [aux_sym_word_token1] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(9),
    [aux_sym_word_token2] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_BSLASH] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(19),
    [anon_sym_BQUOTE] = ACTIONS(21),
    [sym_number] = ACTIONS(23),
  },
  [STATE(3)] = {
    [sym__expr] = STATE(18),
    [sym_word] = STATE(29),
    [sym_symbol] = STATE(29),
    [sym_unquote] = STATE(29),
    [sym_block] = STATE(29),
    [sym_comment] = STATE(3),
    [sym_string] = STATE(29),
    [sym_raw_string] = STATE(29),
    [aux_sym_program_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(27),
    [aux_sym_word_token1] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(9),
    [aux_sym_word_token2] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_BSLASH] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(19),
    [anon_sym_BQUOTE] = ACTIONS(21),
    [sym_number] = ACTIONS(23),
  },
  [STATE(4)] = {
    [sym__expr] = STATE(22),
    [sym_word] = STATE(21),
    [sym_symbol] = STATE(21),
    [sym_unquote] = STATE(21),
    [sym_block] = STATE(21),
    [sym_comment] = STATE(4),
    [sym_string] = STATE(21),
    [sym_raw_string] = STATE(21),
    [aux_sym_program_repeat1] = STATE(5),
    [aux_sym_word_token1] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(31),
    [aux_sym_word_token2] = ACTIONS(29),
    [anon_sym_SQUOTE] = ACTIONS(33),
    [anon_sym_BSLASH] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(37),
    [anon_sym_RBRACK] = ACTIONS(39),
    [anon_sym_LPAREN] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [anon_sym_BQUOTE] = ACTIONS(43),
    [sym_number] = ACTIONS(45),
  },
  [STATE(5)] = {
    [sym__expr] = STATE(22),
    [sym_word] = STATE(21),
    [sym_symbol] = STATE(21),
    [sym_unquote] = STATE(21),
    [sym_block] = STATE(21),
    [sym_comment] = STATE(5),
    [sym_string] = STATE(21),
    [sym_raw_string] = STATE(21),
    [aux_sym_program_repeat1] = STATE(7),
    [aux_sym_word_token1] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(31),
    [aux_sym_word_token2] = ACTIONS(29),
    [anon_sym_SQUOTE] = ACTIONS(33),
    [anon_sym_BSLASH] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(37),
    [anon_sym_RBRACK] = ACTIONS(47),
    [anon_sym_LPAREN] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [anon_sym_BQUOTE] = ACTIONS(43),
    [sym_number] = ACTIONS(45),
  },
  [STATE(6)] = {
    [sym__expr] = STATE(18),
    [sym_word] = STATE(29),
    [sym_symbol] = STATE(29),
    [sym_unquote] = STATE(29),
    [sym_block] = STATE(29),
    [sym_comment] = STATE(6),
    [sym_string] = STATE(29),
    [sym_raw_string] = STATE(29),
    [aux_sym_program_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(49),
    [aux_sym_word_token1] = ACTIONS(51),
    [anon_sym_DASH] = ACTIONS(54),
    [aux_sym_word_token2] = ACTIONS(51),
    [anon_sym_SQUOTE] = ACTIONS(57),
    [anon_sym_BSLASH] = ACTIONS(60),
    [anon_sym_LBRACK] = ACTIONS(63),
    [anon_sym_LPAREN] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(66),
    [anon_sym_BQUOTE] = ACTIONS(69),
    [sym_number] = ACTIONS(72),
  },
  [STATE(7)] = {
    [sym__expr] = STATE(22),
    [sym_word] = STATE(21),
    [sym_symbol] = STATE(21),
    [sym_unquote] = STATE(21),
    [sym_block] = STATE(21),
    [sym_comment] = STATE(7),
    [sym_string] = STATE(21),
    [sym_raw_string] = STATE(21),
    [aux_sym_program_repeat1] = STATE(7),
    [aux_sym_word_token1] = ACTIONS(75),
    [anon_sym_DASH] = ACTIONS(78),
    [aux_sym_word_token2] = ACTIONS(75),
    [anon_sym_SQUOTE] = ACTIONS(81),
    [anon_sym_BSLASH] = ACTIONS(84),
    [anon_sym_LBRACK] = ACTIONS(87),
    [anon_sym_RBRACK] = ACTIONS(49),
    [anon_sym_LPAREN] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(90),
    [anon_sym_BQUOTE] = ACTIONS(93),
    [sym_number] = ACTIONS(96),
  },
  [STATE(8)] = {
    [sym__expr] = STATE(18),
    [sym_word] = STATE(29),
    [sym_symbol] = STATE(29),
    [sym_unquote] = STATE(29),
    [sym_block] = STATE(29),
    [sym_comment] = STATE(8),
    [sym_string] = STATE(29),
    [sym_raw_string] = STATE(29),
    [aux_sym_program_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(99),
    [aux_sym_word_token1] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(9),
    [aux_sym_word_token2] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_BSLASH] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(19),
    [anon_sym_BQUOTE] = ACTIONS(21),
    [sym_number] = ACTIONS(23),
  },
  [STATE(9)] = {
    [sym__expr] = STATE(22),
    [sym_word] = STATE(21),
    [sym_symbol] = STATE(21),
    [sym_unquote] = STATE(21),
    [sym_block] = STATE(21),
    [sym_comment] = STATE(9),
    [sym_string] = STATE(21),
    [sym_raw_string] = STATE(21),
    [aux_sym_program_repeat1] = STATE(10),
    [aux_sym_word_token1] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(31),
    [aux_sym_word_token2] = ACTIONS(29),
    [anon_sym_SQUOTE] = ACTIONS(33),
    [anon_sym_BSLASH] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(37),
    [anon_sym_RBRACK] = ACTIONS(101),
    [anon_sym_LPAREN] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [anon_sym_BQUOTE] = ACTIONS(43),
    [sym_number] = ACTIONS(45),
  },
  [STATE(10)] = {
    [sym__expr] = STATE(22),
    [sym_word] = STATE(21),
    [sym_symbol] = STATE(21),
    [sym_unquote] = STATE(21),
    [sym_block] = STATE(21),
    [sym_comment] = STATE(10),
    [sym_string] = STATE(21),
    [sym_raw_string] = STATE(21),
    [aux_sym_program_repeat1] = STATE(7),
    [aux_sym_word_token1] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(31),
    [aux_sym_word_token2] = ACTIONS(29),
    [anon_sym_SQUOTE] = ACTIONS(33),
    [anon_sym_BSLASH] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(37),
    [anon_sym_RBRACK] = ACTIONS(103),
    [anon_sym_LPAREN] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [anon_sym_BQUOTE] = ACTIONS(43),
    [sym_number] = ACTIONS(45),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(107), 1,
      anon_sym_DASH,
    STATE(11), 1,
      sym_comment,
    ACTIONS(105), 9,
      aux_sym_word_token1,
      aux_sym_word_token2,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [21] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(111), 1,
      anon_sym_DASH,
    STATE(12), 1,
      sym_comment,
    ACTIONS(109), 9,
      ts_builtin_sym_end,
      aux_sym_word_token1,
      aux_sym_word_token2,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [42] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(115), 1,
      anon_sym_DASH,
    STATE(13), 1,
      sym_comment,
    ACTIONS(113), 9,
      ts_builtin_sym_end,
      aux_sym_word_token1,
      aux_sym_word_token2,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [63] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(119), 1,
      anon_sym_DASH,
    STATE(14), 1,
      sym_comment,
    ACTIONS(117), 9,
      ts_builtin_sym_end,
      aux_sym_word_token1,
      aux_sym_word_token2,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [84] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(123), 1,
      anon_sym_DASH,
    STATE(15), 1,
      sym_comment,
    ACTIONS(121), 9,
      ts_builtin_sym_end,
      aux_sym_word_token1,
      aux_sym_word_token2,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [105] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(127), 1,
      anon_sym_DASH,
    STATE(16), 1,
      sym_comment,
    ACTIONS(125), 9,
      ts_builtin_sym_end,
      aux_sym_word_token1,
      aux_sym_word_token2,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [126] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(131), 1,
      anon_sym_DASH,
    STATE(17), 1,
      sym_comment,
    ACTIONS(129), 9,
      ts_builtin_sym_end,
      aux_sym_word_token1,
      aux_sym_word_token2,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [147] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(135), 1,
      anon_sym_DASH,
    STATE(18), 1,
      sym_comment,
    ACTIONS(133), 9,
      ts_builtin_sym_end,
      aux_sym_word_token1,
      aux_sym_word_token2,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [168] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(107), 1,
      anon_sym_DASH,
    STATE(19), 1,
      sym_comment,
    ACTIONS(105), 9,
      ts_builtin_sym_end,
      aux_sym_word_token1,
      aux_sym_word_token2,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [189] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(111), 1,
      anon_sym_DASH,
    STATE(20), 1,
      sym_comment,
    ACTIONS(109), 9,
      aux_sym_word_token1,
      aux_sym_word_token2,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [210] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(139), 1,
      anon_sym_DASH,
    STATE(21), 1,
      sym_comment,
    ACTIONS(137), 9,
      aux_sym_word_token1,
      aux_sym_word_token2,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [231] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(135), 1,
      anon_sym_DASH,
    STATE(22), 1,
      sym_comment,
    ACTIONS(133), 9,
      aux_sym_word_token1,
      aux_sym_word_token2,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [252] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(115), 1,
      anon_sym_DASH,
    STATE(23), 1,
      sym_comment,
    ACTIONS(113), 9,
      aux_sym_word_token1,
      aux_sym_word_token2,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [273] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(119), 1,
      anon_sym_DASH,
    STATE(24), 1,
      sym_comment,
    ACTIONS(117), 9,
      aux_sym_word_token1,
      aux_sym_word_token2,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [294] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(123), 1,
      anon_sym_DASH,
    STATE(25), 1,
      sym_comment,
    ACTIONS(121), 9,
      aux_sym_word_token1,
      aux_sym_word_token2,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [315] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(127), 1,
      anon_sym_DASH,
    STATE(26), 1,
      sym_comment,
    ACTIONS(125), 9,
      aux_sym_word_token1,
      aux_sym_word_token2,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [336] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(131), 1,
      anon_sym_DASH,
    STATE(27), 1,
      sym_comment,
    ACTIONS(129), 9,
      aux_sym_word_token1,
      aux_sym_word_token2,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [357] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(143), 1,
      anon_sym_DASH,
    STATE(28), 1,
      sym_comment,
    ACTIONS(141), 9,
      aux_sym_word_token1,
      aux_sym_word_token2,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [378] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(139), 1,
      anon_sym_DASH,
    STATE(29), 1,
      sym_comment,
    ACTIONS(137), 9,
      ts_builtin_sym_end,
      aux_sym_word_token1,
      aux_sym_word_token2,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [399] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(143), 1,
      anon_sym_DASH,
    STATE(30), 1,
      sym_comment,
    ACTIONS(141), 9,
      ts_builtin_sym_end,
      aux_sym_word_token1,
      aux_sym_word_token2,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [420] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    STATE(31), 1,
      sym_comment,
    ACTIONS(145), 6,
      anon_sym_BSLASH,
      anon_sym_DQUOTE,
      anon_sym_n,
      anon_sym_e,
      anon_sym_r,
      anon_sym_t,
  [435] = 7,
    ACTIONS(147), 1,
      anon_sym_BSLASH,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(151), 1,
      anon_sym_DQUOTE,
    ACTIONS(153), 1,
      aux_sym_string_token1,
    STATE(32), 1,
      sym_comment,
    STATE(33), 1,
      aux_sym_string_repeat1,
    STATE(41), 1,
      sym_string_escape,
  [457] = 6,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(155), 1,
      anon_sym_BSLASH,
    ACTIONS(158), 1,
      anon_sym_DQUOTE,
    ACTIONS(160), 1,
      aux_sym_string_token1,
    STATE(41), 1,
      sym_string_escape,
    STATE(33), 2,
      sym_comment,
      aux_sym_string_repeat1,
  [477] = 7,
    ACTIONS(147), 1,
      anon_sym_BSLASH,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      aux_sym_string_token1,
    ACTIONS(163), 1,
      anon_sym_DQUOTE,
    STATE(33), 1,
      aux_sym_string_repeat1,
    STATE(34), 1,
      sym_comment,
    STATE(41), 1,
      sym_string_escape,
  [499] = 7,
    ACTIONS(147), 1,
      anon_sym_BSLASH,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      aux_sym_string_token1,
    ACTIONS(165), 1,
      anon_sym_DQUOTE,
    STATE(32), 1,
      aux_sym_string_repeat1,
    STATE(35), 1,
      sym_comment,
    STATE(41), 1,
      sym_string_escape,
  [521] = 7,
    ACTIONS(147), 1,
      anon_sym_BSLASH,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      aux_sym_string_token1,
    ACTIONS(167), 1,
      anon_sym_DQUOTE,
    STATE(34), 1,
      aux_sym_string_repeat1,
    STATE(36), 1,
      sym_comment,
    STATE(41), 1,
      sym_string_escape,
  [543] = 5,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_DASH,
    STATE(24), 1,
      sym_word,
    STATE(37), 1,
      sym_comment,
    ACTIONS(29), 2,
      aux_sym_word_token1,
      aux_sym_word_token2,
  [560] = 5,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_DASH,
    STATE(13), 1,
      sym_word,
    STATE(38), 1,
      sym_comment,
    ACTIONS(11), 2,
      aux_sym_word_token1,
      aux_sym_word_token2,
  [577] = 5,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_DASH,
    STATE(14), 1,
      sym_word,
    STATE(39), 1,
      sym_comment,
    ACTIONS(11), 2,
      aux_sym_word_token1,
      aux_sym_word_token2,
  [594] = 5,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_DASH,
    STATE(23), 1,
      sym_word,
    STATE(40), 1,
      sym_comment,
    ACTIONS(29), 2,
      aux_sym_word_token1,
      aux_sym_word_token2,
  [611] = 3,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    STATE(41), 1,
      sym_comment,
    ACTIONS(169), 3,
      anon_sym_BSLASH,
      anon_sym_DQUOTE,
      aux_sym_string_token1,
  [623] = 3,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    STATE(42), 1,
      sym_comment,
    ACTIONS(171), 3,
      anon_sym_BSLASH,
      anon_sym_DQUOTE,
      aux_sym_string_token1,
  [635] = 5,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(173), 1,
      aux_sym_comment_token1,
    ACTIONS(175), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      sym_comment,
    STATE(45), 1,
      aux_sym_comment_repeat1,
  [651] = 5,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(173), 1,
      aux_sym_comment_token1,
    ACTIONS(177), 1,
      anon_sym_RPAREN,
    STATE(44), 1,
      sym_comment,
    STATE(45), 1,
      aux_sym_comment_repeat1,
  [667] = 4,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(179), 1,
      aux_sym_comment_token1,
    ACTIONS(182), 1,
      anon_sym_RPAREN,
    STATE(45), 2,
      sym_comment,
      aux_sym_comment_repeat1,
  [681] = 5,
    ACTIONS(173), 1,
      aux_sym_comment_token1,
    ACTIONS(184), 1,
      anon_sym_LPAREN,
    ACTIONS(186), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      aux_sym_comment_repeat1,
    STATE(46), 1,
      sym_comment,
  [697] = 5,
    ACTIONS(173), 1,
      aux_sym_comment_token1,
    ACTIONS(184), 1,
      anon_sym_LPAREN,
    ACTIONS(188), 1,
      anon_sym_RPAREN,
    STATE(44), 1,
      aux_sym_comment_repeat1,
    STATE(47), 1,
      sym_comment,
  [713] = 4,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(190), 1,
      aux_sym_comment_token1,
    ACTIONS(192), 1,
      anon_sym_RPAREN,
    STATE(48), 1,
      sym_comment,
  [726] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(194), 1,
      anon_sym_RPAREN,
    STATE(49), 1,
      sym_comment,
  [736] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(196), 1,
      anon_sym_BQUOTE,
    STATE(50), 1,
      sym_comment,
  [746] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(198), 1,
      anon_sym_RPAREN,
    STATE(51), 1,
      sym_comment,
  [756] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(200), 1,
      ts_builtin_sym_end,
    STATE(52), 1,
      sym_comment,
  [766] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(202), 1,
      anon_sym_BQUOTE,
    STATE(53), 1,
      sym_comment,
  [776] = 3,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(204), 1,
      sym_raw_string_content,
    STATE(54), 1,
      sym_comment,
  [786] = 3,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(206), 1,
      sym_raw_string_content,
    STATE(55), 1,
      sym_comment,
  [796] = 1,
    ACTIONS(194), 1,
      ts_builtin_sym_end,
  [800] = 1,
    ACTIONS(198), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(11)] = 0,
  [SMALL_STATE(12)] = 21,
  [SMALL_STATE(13)] = 42,
  [SMALL_STATE(14)] = 63,
  [SMALL_STATE(15)] = 84,
  [SMALL_STATE(16)] = 105,
  [SMALL_STATE(17)] = 126,
  [SMALL_STATE(18)] = 147,
  [SMALL_STATE(19)] = 168,
  [SMALL_STATE(20)] = 189,
  [SMALL_STATE(21)] = 210,
  [SMALL_STATE(22)] = 231,
  [SMALL_STATE(23)] = 252,
  [SMALL_STATE(24)] = 273,
  [SMALL_STATE(25)] = 294,
  [SMALL_STATE(26)] = 315,
  [SMALL_STATE(27)] = 336,
  [SMALL_STATE(28)] = 357,
  [SMALL_STATE(29)] = 378,
  [SMALL_STATE(30)] = 399,
  [SMALL_STATE(31)] = 420,
  [SMALL_STATE(32)] = 435,
  [SMALL_STATE(33)] = 457,
  [SMALL_STATE(34)] = 477,
  [SMALL_STATE(35)] = 499,
  [SMALL_STATE(36)] = 521,
  [SMALL_STATE(37)] = 543,
  [SMALL_STATE(38)] = 560,
  [SMALL_STATE(39)] = 577,
  [SMALL_STATE(40)] = 594,
  [SMALL_STATE(41)] = 611,
  [SMALL_STATE(42)] = 623,
  [SMALL_STATE(43)] = 635,
  [SMALL_STATE(44)] = 651,
  [SMALL_STATE(45)] = 667,
  [SMALL_STATE(46)] = 681,
  [SMALL_STATE(47)] = 697,
  [SMALL_STATE(48)] = 713,
  [SMALL_STATE(49)] = 726,
  [SMALL_STATE(50)] = 736,
  [SMALL_STATE(51)] = 746,
  [SMALL_STATE(52)] = 756,
  [SMALL_STATE(53)] = 766,
  [SMALL_STATE(54)] = 776,
  [SMALL_STATE(55)] = 786,
  [SMALL_STATE(56)] = 796,
  [SMALL_STATE(57)] = 800,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 1),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 2, 0, 2),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_string, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_raw_string, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_word, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unquote, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unquote, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 3),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 3),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expr, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 4),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 4),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [155] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [160] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_escape, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [179] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 1, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 1, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [204] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [206] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ripe(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ripe",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
