/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 60
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 1
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_shebang = 1,
  aux_sym_word_token1 = 2,
  anon_sym_DASH = 3,
  aux_sym_word_token2 = 4,
  aux_sym_word_token3 = 5,
  anon_sym_SQUOTE = 6,
  anon_sym_LBRACK = 7,
  anon_sym_RBRACK = 8,
  anon_sym_LPAREN = 9,
  aux_sym_comment_token1 = 10,
  anon_sym_RPAREN = 11,
  anon_sym_BSLASH = 12,
  anon_sym_DQUOTE = 13,
  anon_sym_n = 14,
  anon_sym_e = 15,
  anon_sym_r = 16,
  anon_sym_t = 17,
  aux_sym_string_token1 = 18,
  sym_raw_string_content = 19,
  anon_sym_BQUOTE = 20,
  sym_number = 21,
  sym_program = 22,
  sym__expr = 23,
  sym_word = 24,
  sym_symbol = 25,
  sym_block = 26,
  sym_comment = 27,
  sym_string_escape = 28,
  sym_string = 29,
  sym_raw_string = 30,
  aux_sym_program_repeat1 = 31,
  aux_sym_comment_repeat1 = 32,
  aux_sym_string_repeat1 = 33,
  alias_sym_sentence = 34,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_shebang] = "shebang",
  [aux_sym_word_token1] = "word_token1",
  [anon_sym_DASH] = "-",
  [aux_sym_word_token2] = "word_token2",
  [aux_sym_word_token3] = "word_token3",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_RPAREN] = ")",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_n] = "n",
  [anon_sym_e] = "e",
  [anon_sym_r] = "r",
  [anon_sym_t] = "t",
  [aux_sym_string_token1] = "string_token1",
  [sym_raw_string_content] = "raw_string_content",
  [anon_sym_BQUOTE] = "`",
  [sym_number] = "number",
  [sym_program] = "program",
  [sym__expr] = "_expr",
  [sym_word] = "word",
  [sym_symbol] = "symbol",
  [sym_block] = "block",
  [sym_comment] = "comment",
  [sym_string_escape] = "string_escape",
  [sym_string] = "string",
  [sym_raw_string] = "raw_string",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_comment_repeat1] = "comment_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [alias_sym_sentence] = "sentence",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_shebang] = sym_shebang,
  [aux_sym_word_token1] = aux_sym_word_token1,
  [anon_sym_DASH] = anon_sym_DASH,
  [aux_sym_word_token2] = aux_sym_word_token2,
  [aux_sym_word_token3] = aux_sym_word_token3,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_n] = anon_sym_n,
  [anon_sym_e] = anon_sym_e,
  [anon_sym_r] = anon_sym_r,
  [anon_sym_t] = anon_sym_t,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_raw_string_content] = sym_raw_string_content,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [sym_number] = sym_number,
  [sym_program] = sym_program,
  [sym__expr] = sym__expr,
  [sym_word] = sym_word,
  [sym_symbol] = sym_symbol,
  [sym_block] = sym_block,
  [sym_comment] = sym_comment,
  [sym_string_escape] = sym_string_escape,
  [sym_string] = sym_string,
  [sym_raw_string] = sym_raw_string,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [alias_sym_sentence] = alias_sym_sentence,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_shebang] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_word_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_word_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_word_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_n] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_r] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_t] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_raw_string_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_string_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_sentence] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_content = 1,
  field_string_content = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
  [field_string_content] = "string_content",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [3] = {.index = 0, .length = 1},
  [4] = {.index = 1, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_content, 1},
  [1] =
    {field_string_content, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_sentence,
  },
  [2] = {
    [1] = alias_sym_sentence,
  },
  [3] = {
    [1] = alias_sym_sentence,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym_program_repeat1, 2,
    aux_sym_program_repeat1,
    alias_sym_sentence,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 2,
  [8] = 8,
  [9] = 6,
  [10] = 3,
  [11] = 11,
  [12] = 11,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 13,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 17,
  [24] = 24,
  [25] = 14,
  [26] = 15,
  [27] = 16,
  [28] = 19,
  [29] = 24,
  [30] = 20,
  [31] = 21,
  [32] = 22,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 35,
  [37] = 37,
  [38] = 37,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 41,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 39,
  [47] = 43,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 49,
  [56] = 51,
  [57] = 50,
  [58] = 53,
  [59] = 54,
};

static const TSCharacterRange aux_sym_word_token2_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'#', '&'}, {'*', '/'}, {':', ':'}, {'<', 'Z'}, {'^', '_'},
  {'a', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '"', 30,
        '\'', 21,
        '(', 24,
        ')', 28,
        '-', 18,
        '0', 41,
        '[', 22,
        '\\', 29,
        ']', 23,
        '`', 39,
        'e', 32,
        'n', 31,
        'r', 33,
        't', 34,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != ';') ADVANCE(19);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == '(') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(29);
      if (lookahead == 'e') ADVANCE(32);
      if (lookahead == 'n') ADVANCE(31);
      if (lookahead == 'r') ADVANCE(33);
      if (lookahead == 't') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == '(') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(24);
      if (lookahead == ')') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 4:
      if (lookahead == '(') ADVANCE(24);
      if (lookahead == '-') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (lookahead != 0 &&
          lookahead != '"' &&
          (lookahead < '\'' || ')' < lookahead) &&
          (lookahead < '0' || '9' < lookahead) &&
          lookahead != ';' &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '`') ADVANCE(16);
      END_STATE();
    case 5:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 9:
      if (lookahead == '+' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(40);
      END_STATE();
    case 10:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '"', 30,
        '#', 15,
        '\'', 21,
        '(', 24,
        '-', 18,
        '0', 41,
        '[', 22,
        '`', 39,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (lookahead != 0 &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != ';' &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(16);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '"', 30,
        '\'', 21,
        '(', 24,
        '-', 18,
        '0', 41,
        '[', 22,
        ']', 23,
        '`', 39,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (lookahead != 0 &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != ';' &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(16);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_shebang);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          ('\'' <= lookahead && lookahead <= ')') ||
          lookahead == ';' ||
          ('[' <= lookahead && lookahead <= ']') ||
          lookahead == '`') ADVANCE(14);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_shebang);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (lookahead == '!') ADVANCE(13);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          (lookahead < ' ' || '"' < lookahead) &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != ';' &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '`') ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if ((!eof && set_contains(aux_sym_word_token2_character_set_1, 9, lookahead)) ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '0') ADVANCE(41);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_word_token2);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_word_token3);
      if ((!eof && set_contains(aux_sym_word_token2_character_set_1, 9, lookahead)) ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(38);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(26);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_n);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_e);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_r);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_t);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '(') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(35);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_raw_string_content);
      if (lookahead == '(') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_raw_string_content);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_number);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(6);
      if (lookahead == 'o') ADVANCE(7);
      if (lookahead == 'x') ADVANCE(9);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(6);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 10},
  [2] = {.lex_state = 11},
  [3] = {.lex_state = 11},
  [4] = {.lex_state = 11},
  [5] = {.lex_state = 11},
  [6] = {.lex_state = 11},
  [7] = {.lex_state = 11},
  [8] = {.lex_state = 11},
  [9] = {.lex_state = 11},
  [10] = {.lex_state = 11},
  [11] = {.lex_state = 11},
  [12] = {.lex_state = 11},
  [13] = {.lex_state = 11},
  [14] = {.lex_state = 11},
  [15] = {.lex_state = 11},
  [16] = {.lex_state = 11},
  [17] = {.lex_state = 11},
  [18] = {.lex_state = 11},
  [19] = {.lex_state = 11},
  [20] = {.lex_state = 11},
  [21] = {.lex_state = 11},
  [22] = {.lex_state = 11},
  [23] = {.lex_state = 11},
  [24] = {.lex_state = 11},
  [25] = {.lex_state = 11},
  [26] = {.lex_state = 11},
  [27] = {.lex_state = 11},
  [28] = {.lex_state = 11},
  [29] = {.lex_state = 11},
  [30] = {.lex_state = 11},
  [31] = {.lex_state = 11},
  [32] = {.lex_state = 11},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 20},
  [50] = {.lex_state = 37},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 20},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 37},
  [58] = {(TSStateId)(-1),},
  [59] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [aux_sym_word_token2] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(3),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_n] = ACTIONS(1),
    [anon_sym_e] = ACTIONS(1),
    [anon_sym_r] = ACTIONS(1),
    [anon_sym_t] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_program] = STATE(52),
    [sym__expr] = STATE(14),
    [sym_word] = STATE(29),
    [sym_symbol] = STATE(29),
    [sym_block] = STATE(29),
    [sym_comment] = STATE(1),
    [sym_string] = STATE(29),
    [sym_raw_string] = STATE(29),
    [aux_sym_program_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_shebang] = ACTIONS(7),
    [aux_sym_word_token1] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_BQUOTE] = ACTIONS(19),
    [sym_number] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      aux_sym_word_token1,
    ACTIONS(26), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_SQUOTE,
    ACTIONS(32), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_RBRACK,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(40), 1,
      anon_sym_BQUOTE,
    ACTIONS(43), 1,
      sym_number,
    STATE(25), 1,
      sym__expr,
    STATE(2), 2,
      sym_comment,
      aux_sym_program_repeat1,
    STATE(24), 5,
      sym_word,
      sym_symbol,
      sym_block,
      sym_string,
      sym_raw_string,
  [42] = 13,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      aux_sym_word_token1,
    ACTIONS(48), 1,
      anon_sym_DASH,
    ACTIONS(50), 1,
      anon_sym_SQUOTE,
    ACTIONS(52), 1,
      anon_sym_LBRACK,
    ACTIONS(54), 1,
      anon_sym_RBRACK,
    ACTIONS(56), 1,
      anon_sym_DQUOTE,
    ACTIONS(58), 1,
      anon_sym_BQUOTE,
    ACTIONS(60), 1,
      sym_number,
    STATE(3), 1,
      sym_comment,
    STATE(6), 1,
      aux_sym_program_repeat1,
    STATE(25), 1,
      sym__expr,
    STATE(24), 5,
      sym_word,
      sym_symbol,
      sym_block,
      sym_string,
      sym_raw_string,
  [86] = 13,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_BQUOTE,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(62), 1,
      ts_builtin_sym_end,
    ACTIONS(64), 1,
      aux_sym_word_token1,
    STATE(4), 1,
      sym_comment,
    STATE(7), 1,
      aux_sym_program_repeat1,
    STATE(14), 1,
      sym__expr,
    STATE(29), 5,
      sym_word,
      sym_symbol,
      sym_block,
      sym_string,
      sym_raw_string,
  [130] = 13,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_BQUOTE,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(64), 1,
      aux_sym_word_token1,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
    STATE(5), 1,
      sym_comment,
    STATE(7), 1,
      aux_sym_program_repeat1,
    STATE(14), 1,
      sym__expr,
    STATE(29), 5,
      sym_word,
      sym_symbol,
      sym_block,
      sym_string,
      sym_raw_string,
  [174] = 13,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      aux_sym_word_token1,
    ACTIONS(48), 1,
      anon_sym_DASH,
    ACTIONS(50), 1,
      anon_sym_SQUOTE,
    ACTIONS(52), 1,
      anon_sym_LBRACK,
    ACTIONS(56), 1,
      anon_sym_DQUOTE,
    ACTIONS(58), 1,
      anon_sym_BQUOTE,
    ACTIONS(60), 1,
      sym_number,
    ACTIONS(68), 1,
      anon_sym_RBRACK,
    STATE(2), 1,
      aux_sym_program_repeat1,
    STATE(6), 1,
      sym_comment,
    STATE(25), 1,
      sym__expr,
    STATE(24), 5,
      sym_word,
      sym_symbol,
      sym_block,
      sym_string,
      sym_raw_string,
  [218] = 12,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    ACTIONS(70), 1,
      aux_sym_word_token1,
    ACTIONS(73), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      anon_sym_SQUOTE,
    ACTIONS(79), 1,
      anon_sym_LBRACK,
    ACTIONS(82), 1,
      anon_sym_DQUOTE,
    ACTIONS(85), 1,
      anon_sym_BQUOTE,
    ACTIONS(88), 1,
      sym_number,
    STATE(14), 1,
      sym__expr,
    STATE(7), 2,
      sym_comment,
      aux_sym_program_repeat1,
    STATE(29), 5,
      sym_word,
      sym_symbol,
      sym_block,
      sym_string,
      sym_raw_string,
  [260] = 13,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_BQUOTE,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(64), 1,
      aux_sym_word_token1,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
    STATE(5), 1,
      aux_sym_program_repeat1,
    STATE(8), 1,
      sym_comment,
    STATE(14), 1,
      sym__expr,
    STATE(29), 5,
      sym_word,
      sym_symbol,
      sym_block,
      sym_string,
      sym_raw_string,
  [304] = 13,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      aux_sym_word_token1,
    ACTIONS(48), 1,
      anon_sym_DASH,
    ACTIONS(50), 1,
      anon_sym_SQUOTE,
    ACTIONS(52), 1,
      anon_sym_LBRACK,
    ACTIONS(56), 1,
      anon_sym_DQUOTE,
    ACTIONS(58), 1,
      anon_sym_BQUOTE,
    ACTIONS(60), 1,
      sym_number,
    ACTIONS(93), 1,
      anon_sym_RBRACK,
    STATE(2), 1,
      aux_sym_program_repeat1,
    STATE(9), 1,
      sym_comment,
    STATE(25), 1,
      sym__expr,
    STATE(24), 5,
      sym_word,
      sym_symbol,
      sym_block,
      sym_string,
      sym_raw_string,
  [348] = 13,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      aux_sym_word_token1,
    ACTIONS(48), 1,
      anon_sym_DASH,
    ACTIONS(50), 1,
      anon_sym_SQUOTE,
    ACTIONS(52), 1,
      anon_sym_LBRACK,
    ACTIONS(56), 1,
      anon_sym_DQUOTE,
    ACTIONS(58), 1,
      anon_sym_BQUOTE,
    ACTIONS(60), 1,
      sym_number,
    ACTIONS(95), 1,
      anon_sym_RBRACK,
    STATE(9), 1,
      aux_sym_program_repeat1,
    STATE(10), 1,
      sym_comment,
    STATE(25), 1,
      sym__expr,
    STATE(24), 5,
      sym_word,
      sym_symbol,
      sym_block,
      sym_string,
      sym_raw_string,
  [392] = 5,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(99), 1,
      anon_sym_DASH,
    ACTIONS(101), 1,
      aux_sym_word_token2,
    STATE(11), 1,
      sym_comment,
    ACTIONS(97), 7,
      ts_builtin_sym_end,
      aux_sym_word_token1,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [414] = 5,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(99), 1,
      anon_sym_DASH,
    ACTIONS(103), 1,
      aux_sym_word_token2,
    STATE(12), 1,
      sym_comment,
    ACTIONS(97), 7,
      aux_sym_word_token1,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [436] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(107), 1,
      anon_sym_DASH,
    STATE(13), 1,
      sym_comment,
    ACTIONS(105), 7,
      aux_sym_word_token1,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [455] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(111), 1,
      anon_sym_DASH,
    STATE(14), 1,
      sym_comment,
    ACTIONS(109), 7,
      ts_builtin_sym_end,
      aux_sym_word_token1,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [474] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(115), 1,
      anon_sym_DASH,
    STATE(15), 1,
      sym_comment,
    ACTIONS(113), 7,
      ts_builtin_sym_end,
      aux_sym_word_token1,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [493] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(119), 1,
      anon_sym_DASH,
    STATE(16), 1,
      sym_comment,
    ACTIONS(117), 7,
      ts_builtin_sym_end,
      aux_sym_word_token1,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [512] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(99), 1,
      anon_sym_DASH,
    STATE(17), 1,
      sym_comment,
    ACTIONS(97), 7,
      ts_builtin_sym_end,
      aux_sym_word_token1,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [531] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(107), 1,
      anon_sym_DASH,
    STATE(18), 1,
      sym_comment,
    ACTIONS(105), 7,
      ts_builtin_sym_end,
      aux_sym_word_token1,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [550] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(123), 1,
      anon_sym_DASH,
    STATE(19), 1,
      sym_comment,
    ACTIONS(121), 7,
      ts_builtin_sym_end,
      aux_sym_word_token1,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [569] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(127), 1,
      anon_sym_DASH,
    STATE(20), 1,
      sym_comment,
    ACTIONS(125), 7,
      ts_builtin_sym_end,
      aux_sym_word_token1,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [588] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(131), 1,
      anon_sym_DASH,
    STATE(21), 1,
      sym_comment,
    ACTIONS(129), 7,
      ts_builtin_sym_end,
      aux_sym_word_token1,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [607] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(135), 1,
      anon_sym_DASH,
    STATE(22), 1,
      sym_comment,
    ACTIONS(133), 7,
      ts_builtin_sym_end,
      aux_sym_word_token1,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [626] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(99), 1,
      anon_sym_DASH,
    STATE(23), 1,
      sym_comment,
    ACTIONS(97), 7,
      aux_sym_word_token1,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [645] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(139), 1,
      anon_sym_DASH,
    STATE(24), 1,
      sym_comment,
    ACTIONS(137), 7,
      aux_sym_word_token1,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [664] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(111), 1,
      anon_sym_DASH,
    STATE(25), 1,
      sym_comment,
    ACTIONS(109), 7,
      aux_sym_word_token1,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [683] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(115), 1,
      anon_sym_DASH,
    STATE(26), 1,
      sym_comment,
    ACTIONS(113), 7,
      aux_sym_word_token1,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [702] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(119), 1,
      anon_sym_DASH,
    STATE(27), 1,
      sym_comment,
    ACTIONS(117), 7,
      aux_sym_word_token1,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [721] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(123), 1,
      anon_sym_DASH,
    STATE(28), 1,
      sym_comment,
    ACTIONS(121), 7,
      aux_sym_word_token1,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [740] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(139), 1,
      anon_sym_DASH,
    STATE(29), 1,
      sym_comment,
    ACTIONS(137), 7,
      ts_builtin_sym_end,
      aux_sym_word_token1,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [759] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(127), 1,
      anon_sym_DASH,
    STATE(30), 1,
      sym_comment,
    ACTIONS(125), 7,
      aux_sym_word_token1,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [778] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(131), 1,
      anon_sym_DASH,
    STATE(31), 1,
      sym_comment,
    ACTIONS(129), 7,
      aux_sym_word_token1,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [797] = 4,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(135), 1,
      anon_sym_DASH,
    STATE(32), 1,
      sym_comment,
    ACTIONS(133), 7,
      aux_sym_word_token1,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      sym_number,
  [816] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    STATE(33), 1,
      sym_comment,
    ACTIONS(141), 6,
      anon_sym_BSLASH,
      anon_sym_DQUOTE,
      anon_sym_n,
      anon_sym_e,
      anon_sym_r,
      anon_sym_t,
  [831] = 6,
    ACTIONS(143), 1,
      anon_sym_LPAREN,
    ACTIONS(145), 1,
      anon_sym_BSLASH,
    ACTIONS(148), 1,
      anon_sym_DQUOTE,
    ACTIONS(150), 1,
      aux_sym_string_token1,
    STATE(44), 1,
      sym_string_escape,
    STATE(34), 2,
      sym_comment,
      aux_sym_string_repeat1,
  [851] = 7,
    ACTIONS(143), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_BSLASH,
    ACTIONS(155), 1,
      anon_sym_DQUOTE,
    ACTIONS(157), 1,
      aux_sym_string_token1,
    STATE(35), 1,
      sym_comment,
    STATE(37), 1,
      aux_sym_string_repeat1,
    STATE(44), 1,
      sym_string_escape,
  [873] = 7,
    ACTIONS(143), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_BSLASH,
    ACTIONS(157), 1,
      aux_sym_string_token1,
    ACTIONS(159), 1,
      anon_sym_DQUOTE,
    STATE(36), 1,
      sym_comment,
    STATE(38), 1,
      aux_sym_string_repeat1,
    STATE(44), 1,
      sym_string_escape,
  [895] = 7,
    ACTIONS(143), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_BSLASH,
    ACTIONS(157), 1,
      aux_sym_string_token1,
    ACTIONS(161), 1,
      anon_sym_DQUOTE,
    STATE(34), 1,
      aux_sym_string_repeat1,
    STATE(37), 1,
      sym_comment,
    STATE(44), 1,
      sym_string_escape,
  [917] = 7,
    ACTIONS(143), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_BSLASH,
    ACTIONS(157), 1,
      aux_sym_string_token1,
    ACTIONS(163), 1,
      anon_sym_DQUOTE,
    STATE(34), 1,
      aux_sym_string_repeat1,
    STATE(38), 1,
      sym_comment,
    STATE(44), 1,
      sym_string_escape,
  [939] = 5,
    ACTIONS(143), 1,
      anon_sym_LPAREN,
    ACTIONS(165), 1,
      aux_sym_comment_token1,
    ACTIONS(167), 1,
      anon_sym_RPAREN,
    STATE(39), 1,
      sym_comment,
    STATE(40), 1,
      aux_sym_comment_repeat1,
  [955] = 4,
    ACTIONS(143), 1,
      anon_sym_LPAREN,
    ACTIONS(169), 1,
      aux_sym_comment_token1,
    ACTIONS(172), 1,
      anon_sym_RPAREN,
    STATE(40), 2,
      sym_comment,
      aux_sym_comment_repeat1,
  [969] = 5,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      aux_sym_word_token1,
    ACTIONS(174), 1,
      anon_sym_DASH,
    STATE(26), 1,
      sym_word,
    STATE(41), 1,
      sym_comment,
  [985] = 5,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(64), 1,
      aux_sym_word_token1,
    ACTIONS(176), 1,
      anon_sym_DASH,
    STATE(15), 1,
      sym_word,
    STATE(42), 1,
      sym_comment,
  [1001] = 5,
    ACTIONS(165), 1,
      aux_sym_comment_token1,
    ACTIONS(178), 1,
      anon_sym_LPAREN,
    ACTIONS(180), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      sym_comment,
    STATE(46), 1,
      aux_sym_comment_repeat1,
  [1017] = 3,
    ACTIONS(143), 1,
      anon_sym_LPAREN,
    STATE(44), 1,
      sym_comment,
    ACTIONS(182), 3,
      anon_sym_BSLASH,
      anon_sym_DQUOTE,
      aux_sym_string_token1,
  [1029] = 3,
    ACTIONS(143), 1,
      anon_sym_LPAREN,
    STATE(45), 1,
      sym_comment,
    ACTIONS(184), 3,
      anon_sym_BSLASH,
      anon_sym_DQUOTE,
      aux_sym_string_token1,
  [1041] = 5,
    ACTIONS(143), 1,
      anon_sym_LPAREN,
    ACTIONS(165), 1,
      aux_sym_comment_token1,
    ACTIONS(186), 1,
      anon_sym_RPAREN,
    STATE(40), 1,
      aux_sym_comment_repeat1,
    STATE(46), 1,
      sym_comment,
  [1057] = 5,
    ACTIONS(165), 1,
      aux_sym_comment_token1,
    ACTIONS(178), 1,
      anon_sym_LPAREN,
    ACTIONS(188), 1,
      anon_sym_RPAREN,
    STATE(39), 1,
      aux_sym_comment_repeat1,
    STATE(47), 1,
      sym_comment,
  [1073] = 4,
    ACTIONS(143), 1,
      anon_sym_LPAREN,
    ACTIONS(190), 1,
      aux_sym_comment_token1,
    ACTIONS(192), 1,
      anon_sym_RPAREN,
    STATE(48), 1,
      sym_comment,
  [1086] = 3,
    ACTIONS(143), 1,
      anon_sym_LPAREN,
    ACTIONS(194), 1,
      aux_sym_word_token3,
    STATE(49), 1,
      sym_comment,
  [1096] = 3,
    ACTIONS(143), 1,
      anon_sym_LPAREN,
    ACTIONS(196), 1,
      sym_raw_string_content,
    STATE(50), 1,
      sym_comment,
  [1106] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(198), 1,
      anon_sym_BQUOTE,
    STATE(51), 1,
      sym_comment,
  [1116] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(200), 1,
      ts_builtin_sym_end,
    STATE(52), 1,
      sym_comment,
  [1126] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(202), 1,
      anon_sym_RPAREN,
    STATE(53), 1,
      sym_comment,
  [1136] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(204), 1,
      anon_sym_RPAREN,
    STATE(54), 1,
      sym_comment,
  [1146] = 3,
    ACTIONS(143), 1,
      anon_sym_LPAREN,
    ACTIONS(206), 1,
      aux_sym_word_token3,
    STATE(55), 1,
      sym_comment,
  [1156] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(208), 1,
      anon_sym_BQUOTE,
    STATE(56), 1,
      sym_comment,
  [1166] = 3,
    ACTIONS(143), 1,
      anon_sym_LPAREN,
    ACTIONS(210), 1,
      sym_raw_string_content,
    STATE(57), 1,
      sym_comment,
  [1176] = 1,
    ACTIONS(202), 1,
      ts_builtin_sym_end,
  [1180] = 1,
    ACTIONS(204), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 42,
  [SMALL_STATE(4)] = 86,
  [SMALL_STATE(5)] = 130,
  [SMALL_STATE(6)] = 174,
  [SMALL_STATE(7)] = 218,
  [SMALL_STATE(8)] = 260,
  [SMALL_STATE(9)] = 304,
  [SMALL_STATE(10)] = 348,
  [SMALL_STATE(11)] = 392,
  [SMALL_STATE(12)] = 414,
  [SMALL_STATE(13)] = 436,
  [SMALL_STATE(14)] = 455,
  [SMALL_STATE(15)] = 474,
  [SMALL_STATE(16)] = 493,
  [SMALL_STATE(17)] = 512,
  [SMALL_STATE(18)] = 531,
  [SMALL_STATE(19)] = 550,
  [SMALL_STATE(20)] = 569,
  [SMALL_STATE(21)] = 588,
  [SMALL_STATE(22)] = 607,
  [SMALL_STATE(23)] = 626,
  [SMALL_STATE(24)] = 645,
  [SMALL_STATE(25)] = 664,
  [SMALL_STATE(26)] = 683,
  [SMALL_STATE(27)] = 702,
  [SMALL_STATE(28)] = 721,
  [SMALL_STATE(29)] = 740,
  [SMALL_STATE(30)] = 759,
  [SMALL_STATE(31)] = 778,
  [SMALL_STATE(32)] = 797,
  [SMALL_STATE(33)] = 816,
  [SMALL_STATE(34)] = 831,
  [SMALL_STATE(35)] = 851,
  [SMALL_STATE(36)] = 873,
  [SMALL_STATE(37)] = 895,
  [SMALL_STATE(38)] = 917,
  [SMALL_STATE(39)] = 939,
  [SMALL_STATE(40)] = 955,
  [SMALL_STATE(41)] = 969,
  [SMALL_STATE(42)] = 985,
  [SMALL_STATE(43)] = 1001,
  [SMALL_STATE(44)] = 1017,
  [SMALL_STATE(45)] = 1029,
  [SMALL_STATE(46)] = 1041,
  [SMALL_STATE(47)] = 1057,
  [SMALL_STATE(48)] = 1073,
  [SMALL_STATE(49)] = 1086,
  [SMALL_STATE(50)] = 1096,
  [SMALL_STATE(51)] = 1106,
  [SMALL_STATE(52)] = 1116,
  [SMALL_STATE(53)] = 1126,
  [SMALL_STATE(54)] = 1136,
  [SMALL_STATE(55)] = 1146,
  [SMALL_STATE(56)] = 1156,
  [SMALL_STATE(57)] = 1166,
  [SMALL_STATE(58)] = 1176,
  [SMALL_STATE(59)] = 1180,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 1),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 2, 0, 2),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_word, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 4),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 4),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_word, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 3),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 3),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_string, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_raw_string, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expr, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [145] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [150] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 1, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_escape, 2, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 1, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 1, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [196] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [200] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [210] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ripe(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ripe",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
